#!/bin/bash

#============================================FUNCTIONS==============================================
usage()
{
  echo "$0 is a tool to get a piece of information from Jenkins slaves
WARNING: MAKE SURE TO WRAP YOUR ACTION/LABEL IN SINGLE QUOTES
--------------------------------------------------------------------------
USAGE: $0 -a 'ACTION' -l 'LABEL' -d|-i|-p|-r|-s|-t|-j JENKINS_URL AUTH_TOKEN
  -a     #defines the list of actions to perform on the remote host 
  -d     #use the development Jenkins (${DEV_URL})
  -g     #use the development Jenkins in Lebanon (${G_W_URL})
  -i     #use the continuous integration Jenkins (${INT_URL})
  -j     #specify the exact Jenkins URL and username:API Token to access
  -l     #Use a label restriction, as in Jenkins (eg lin64&&test)
  -p     #use the profiling Jenkins (${PRF_URL})
  -r     #use the release Jenkins (${REL_URL})
  -s     #use starci jenkins (${STR_URL})
  -t     #use the third party build jenkins (${TPB_URL})
"
  echo $*
  exit 1
}

get_all_slaves()
{
  SLAVE_LIST="$(curl -s "${JENKINS_URL}/computer/api/xml?tree=computer\[displayName\]" -u ${AUTH_TOKEN} | tr '<' '\n' | grep ^displayName | cut -d '>' -f 2 | sort | tr '\n' ' ')"

  #remove slaves ssh: Could not resolve hostname
  SLAVE_LIST=${SLAVE_LIST/atom /}
  SLAVE_LIST=${SLAVE_LIST/icr /}
  
  #remove slaves that can resolve but test password doesn't work
  SLAVE_LIST=${SLAVE_LIST/getafix /}
  SLAVE_LIST=${SLAVE_LIST/hyper /}
  SLAVE_LIST=${SLAVE_LIST/keith /}
  SLAVE_LIST=${SLAVE_LIST/linperf /}  
  SLAVE_LIST=${SLAVE_LIST/marlin /}
  SLAVE_LIST=${SLAVE_LIST/soraya /}

  #remove slaves BrianH has no business being on 
  SLAVE_LIST=${SLAVE_LIST/master /}     #no one should tinker with the master
  SLAVE_LIST=${SLAVE_LIST/gowri_iron /} #gowri's personal machine
  SLAVE_LIST=${SLAVE_LIST/pw-pc /}      #peter's personal machine

  #remove servers
  SLAVE_LIST=${SLAVE_LIST/austinsrv /}
  SLAVE_LIST=${SLAVE_LIST/detroitsrv /}
  SLAVE_LIST=${SLAVE_LIST/houstonsrv /}
  SLAVE_LIST=${SLAVE_LIST/houstonsrv.old /}
  SLAVE_LIST=${SLAVE_LIST/irvinesrv /}
  SLAVE_LIST=${SLAVE_LIST/orlandosrv /}
  SLAVE_LIST=${SLAVE_LIST/osaka01 /}
  SLAVE_LIST=${SLAVE_LIST/rome /}
  SLAVE_LIST=${SLAVE_LIST/seattlesrv /}
  SLAVE_LIST=${SLAVE_LIST/statecollegesrv /}
  SLAVE_LIST=${SLAVE_LIST/tulsasrv /}
  SLAVE_LIST=${SLAVE_LIST/turin /}
  SLAVE_LIST=${SLAVE_LIST/vm-jenkins-ny /}
  SLAVE_LIST=${SLAVE_LIST/yokohama04 /}

  #Jenkins has the name wrong
  SLAVE_LIST=${SLAVE_LIST/win64builder02x/win64builder}

  #DORY is currently offline
  SLAVE_LIST=${SLAVE_LIST/dory /}
}

get_label_slaves()
{
  SLAVE_LIST="$(curl -s "${JENKINS_URL}/label/${LABEL}/api/xml?tree=nodes\[nodeName\]" -u ${AUTH_TOKEN} | tr '<' '\n' | grep ^nodeName | cut -d '>' -f 2 | sort | tr '\n' ' ')"
}

ssh_as_test()
{ 
  FQDN=${JENKINS_URL}
  FQDN=${FQDN#*.}
  echo "ACTION=${ACTION} USING SSH ARGS ${PASSTHROUGH_ARGS}"
  for SLAVE in ${SLAVE_LIST}; do
    echo -n "${SLAVE}: "
   
    ssh ${PASSTHROUGH_ARGS} test@${SLAVE}.${FQDN} "${ACTION}" ${PARALLEL}
  done

}

process_arguments()
{
  while [ $# -gt 0 ]; do
    case "$1" in
      -h|--help)
        usage
      ;;
      -a|-A)
        ACTION=$2
        shift
      ;;
      -d|-D)
        JENKINS_URL=${DEV_URL}
        AUTH_TOKEN=test:a863cafc46e58140bfcb6490f4561b1c
      ;;
      -g|-G)
        JENKINS_URL=${G_W_URL}
        AUTH_TOKEN=test:3f3e8c7f055223bc6a9c82be48191fdd
      ;;
      -i|-I)
        JENKINS_URL=${INT_URL}
        AUTH_TOKEN=test:2d3ed74578d566426d37c2ae6add8e0f
      ;;
      -j|-J)
        JENKINS_URL=$2
      ;;
      -l|-L)
        LABEL=$2
        ASK_ALL=false
        shift
      ;;
      -p|-P)
        JENKINS_URL=${PRF_URL}
        AUTH_TOKEN=test:02859465a6535f7ba6ce1380b0085e0d
      ;;
      -r|-R)
        JENKINS_URL=${REL_URL}
        AUTH_TOKEN=test:66a729e77080fc2285b362fdda2f6d33
      ;;
      -s|-S)
        JENKINS_URL=${STR_URL}
        AUTH_TOKEN=test:88257d321f7afe0920bfc9ac894073b1
      ;;
      -t|-T)
        JENKINS_URL=${TPB_URL}
        AUTH_TOKEN=test:16d7f836562ed9ea3c90403d4b1f76d0
      ;;
      -z|-Z)
        PARALLEL="&"
      ;;
      *)
        PASSTHROUGH_ARGS="${PASSTHROUGH_ARGS} $1"
      ;;
    esac
    shift
  done
  if [ -z "${ACTION}" ]; then
    usage "NO ACTION specified"
  fi
  if [ ${ASK_ALL} = false ] && [ -z ${LABEL} ] ; then
    usage "No label specified"
  fi
  if [ -z "${JENKINS_URL}" ]; then
    usage "No JENKINS instance specified"
  fi
  if [ -z "${AUTH_TOKEN}" ]; then
    usage "No CREDENTIALS specified to gain access to ${JENKINS_URL}"
  fi
}
#==========================================END FUNCTIONS============================================

ACTION=""
ASK_ALL=true
DEV_URL="http://devci.dev.cd-adapco.com"
G_W_URL="http://devci.lebanon.cd-adapco.com"
INT_URL="http://intci.lebanon.cd-adapco.com"
JENKINS_URL=""
PARALLEL=""
PASSTHROUGH_ARGS=""
PRF_URL="http://intci-dev.lebanon.cd-adapco.com"
REL_URL="http://relci.lebanon.cd-adapco.com"
STR_URL="http://starci.lebanon.cd-adapco.com"
TPB_URL="http://tpb.lebanon.cd-adapco.com"

if [ $# -lt 1 ]; then
  usage "No arguments specified"
fi

process_arguments "$@"

if [ ${ASK_ALL} = true ]; then
  get_all_slaves
else
  get_label_slaves
fi
ssh_as_test
