#!/bin/sh -e

#============================================FUNCTIONS==============================================
usage()
{
  echo "$0 is a tool to backup my bin and test directories
--------------------------------------------------------------------------
USAGE: $0 
       #I don't take any arguments
"
  echo "$*"
  exit 1
}

back_it_up()
{
  for ITEM in ${BACKUP_LIST}; do
    echo "Making 7z for ${ITEM}"
    7za a ${LOCAL_BACKUP}/${DATE}/${ITEM}.7z ~/${ITEM} > ${LOCAL_BACKUP}/${DATE}/${ITEM}.log
    du -sh ${LOCAL_BACKUP}/${DATE}/${ITEM}.7z
  done
}

create_backup_loc()
{

  if [ ! -d ${LOCAL_BACKUP}/${DATE} ]; then
    echo "Making dir ${LOCAL_BACKUP}/${DATE}"
    mkdir -p ${LOCAL_BACKUP}/${DATE}
  fi 

}

remove_old_backups()
{
  if [ $(ls -1t ${LOCAL_BACKUP} | wc -l ) -gt ${NUMBER_TO_KEEP} ]; then
    ls -1tr ${LOCAL_BACKUP} | head -n -${NUMBER_TO_KEEP} | while read BACKUP_NUMBER; do
      echo "Deleting Backup ${BACKUP_NUMBER}"
      rm -rf ${LOCAL_BACKUP}/${BACKUP_NUMBER}
    done
  fi
}

sync_local_and_offsite()
{
  echo "Syncing to ${MOUNT}"
  rsync -hav --delete --progress ${LOCAL_BACKUP}/ ${OFFSITE_BACKUP}/
}

process_arguments()
{
  while [ $# -gt 0 ]; do
    case "$1" in
      -h|--help)
        usage
      ;;
    esac
    shift
  done
}
#==========================================END FUNCTIONS============================================
LOCAL_BACKUP=${HOME}/.backup
OFFSITE_BACKUP=brianh@nas03:/srv/users/brianh/.backup

DATE=$(date +%Y%m%d%H%M%S)

BACKUP_LIST="bin DevOps keys MGMT test update_jenkins_configs VMWIMP .ssh .bashrc privateData Templates"


NUMBER_TO_KEEP=5


#if [ $# -lt 1 ]; then
#  usage "No arguments specified"
#fi

process_arguments "$@"
create_backup_loc
back_it_up
remove_old_backups
sync_local_and_offsite
