#!/bin/bash
GIT=$1
CURRENT_DIR=$(pwd)
TYPE=""
#============================================FUNCTIONS==============================================
usage()
{
  echo "Usage: $0  GIT_REPO
  GIT_REPO   #this should be a local working copy (clone) of a git/gitfat repo
"
  echo $*

  exit 1

}

is_git_repo()
{
  if [ ! -d ${CURRENT_DIR}/${GIT} ]; then
    usage "No directory exists at ${CURRENT_DIR}/${GIT}"
  fi
  if [ ! -d ${CURRENT_DIR}/${GIT}/.git ]; then
    usage "${CURRENT_DIR}/${GIT} is not a git repository"
  fi
  TYPE=GIT
}

is_git_fat_repo()
{
  if [ -f  ${CURRENT_DIR}/${GIT}/.gitfat ]; then
    TYPE=FAT
  fi
}

nuke_repo()
{
  rm -rf ${GIT}
}

remake_repo()
{
  git clone git@stash:ups/${GIT}.git
  cd ${GIT}
  if [ "$TYPE" = "FAT" ]; then
    git fat init
  fi
  git pull
  git status
  cd ${CURRENT_DIR}
}
#==========================================END=FUNCTIONS============================================
GIT=${GIT%/}
is_git_repo
is_git_fat_repo
nuke_repo
remake_repo

if [ "${GIT}" = "star" ]; then
  cd ${CURRENT_DIR}
  chmod 750 ${GIT}
fi
